apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cert-manager-webhook-ns1.fullname" . }}
  labels:
    app: {{ include "cert-manager-webhook-ns1.name" . }}
    chart: {{ include "cert-manager-webhook-ns1.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
# Grant the webhook permission to read the ConfigMap containing the Kubernetes
# apiserver's requestheader-ca-certificate.
# This ConfigMap is automatically created by the Kubernetes apiserver.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cert-manager-webhook-ns1.fullname" . }}:webhook-authentication-reader
  namespace: kube-system
  labels:
    app: {{ include "cert-manager-webhook-ns1.name" . }}
    chart: {{ include "cert-manager-webhook-ns1.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "cert-manager-webhook-ns1.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
# apiserver gets the auth-delegator role to delegate auth decisions to
# the core apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cert-manager-webhook-ns1.fullname" . }}:auth-delegator
  labels:
    app: {{ include "cert-manager-webhook-ns1.name" . }}
    chart: {{ include "cert-manager-webhook-ns1.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "cert-manager-webhook-ns1.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
# Grant cert-manager permission to validate using our apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cert-manager-webhook-ns1.fullname" . }}:domain-solver
  labels:
    app: {{ include "cert-manager-webhook-ns1.name" . }}
    chart: {{ include "cert-manager-webhook-ns1.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - {{ .Values.groupName }}
    resources:
      - '*'
    verbs:
      - 'create'
---
# Grant NS1 webhook permission to read the cert secret
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cert-manager-webhook-ns1.fullname" . }}
  labels:
    app: {{ include "cert-manager-webhook-ns1.name" . }}
    chart: {{ include "cert-manager-webhook-ns1.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
  # K8s 1.15.8 and below has a bug noted here: https://github.com/kubernetes/kubernetes/issues/86359
  # A fix was merged in this PR: https://github.com/kubernetes/kubernetes/pull/86363/files, and k8s version 1.15.9+ has the fix
  # For backwards compatability, the ClusterRole is modified to allow for configmap access.
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cert-manager-webhook-ns1.fullname" . }}:domain-solver
  labels:
    app: {{ include "cert-manager-webhook-ns1.name" . }}
    chart: {{ include "cert-manager-webhook-ns1.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cert-manager-webhook-ns1.fullname" . }}:domain-solver
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ .Values.certManager.serviceAccountName }}
    namespace: {{ .Values.certManager.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cert-manager-webhook-ns1.fullname" . }}
  labels:
    app: {{ include "cert-manager-webhook-ns1.name" . }}
    chart: {{ include "cert-manager-webhook-ns1.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cert-manager-webhook-ns1.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "cert-manager-webhook-ns1.fullname" . }}
    namespace: {{ .Release.Namespace }}
